### ISSUE TITLE
Add summary description to READ.ME

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/clingen-knowledge#1]
Need one or two sentences at top of readme to describe what this repo actually contains.  Ideally, we would rename this to something with that starts with "website". But if the summary description contains the term website that will help find this repo when doing a search on repos for that term.

At a minimum please add a couple sentences at the top of the READ.ME file to make sure folks can understand what is in this repo.

**Comment by sgoehringer** [comment]
@larrybabb confirm the summary added is satisfactory.  If so, feel free to close.
