### ISSUE TITLE
Gene Curation update for PMS2 - Gene Disease Validity

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#18]
We have been asked by Deb Ritter to remove a legacy curation for "PMS2 - colorectal cancer, hereditary nonpolyposis, type 4 | MONDO:0013699".  Since this is a legacy curation and prior to the conversion to MONDO this requires that the reference to OMIM:614337 on curation 9851 (https://search.clinicalgenome.org/kb/gene-validity/9851) is removed.  This was removed from the JSON file in the following commit (https://github.com/clingen-data-model/data-exchange-shared-json/commit/6a2a9d72bfafb9408d7de03ffe258fadc16c34cd)

@tnavatar recommends that we make a manual database change remove this relationship. Tristan will share the steps completed to make this manual change with @plweller3 so staging databases are kept in sync. 

Review the email that was sent with the subject of "Fwd: PMS2 on ClinGen Website " and relay any questions/concerns.

**Comment by tnavatar** [comment]
Performed the following operation on the production neo4j database to remove the relevant relation:

neo4j> match (c:GeneDiseaseAssertion {perm_id: "9851"})-[rel:has_object]->(d {iri: "http://purl.obolibrary.org/obo/MONDO_0013699"}) delete rel;
0 rows available after 52 ms, consumed after another 0 ms
Deleted 1 relationships

**Comment by sgoehringer** [comment]
@tnavatar thanks!  I checked a non-cached page and it was dropped.  Cached pages still show things but I will recheck later/tomorrow.  I will close ticket after confirming it isn't showing.

NOTE, I also followed back up with Deb R.
