### ISSUE TITLE
Gene Curation update for PMS2 - Dosage

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#20]
This issue is a placeholder/reminder if the Dosage team recommends updates based on a the "PMS2 on ClinGen Website" request.

**Comment by sgoehringer** [comment]
Note - the dosage team was contacted and it will be a topic for Nov 21 or 22 calls

**Comment by tnavatar** [comment]
FWIW the Lynch syndrome Orpha/MONDO term used in this curation does not link directly to an OMIM term: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005835 <https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0005835>

Until dosage curations are allowed directly against MONDO terms, it will not be an option for them to link directly to Lynch syndrome

**Comment by sgoehringer** [comment]
@tnavatar thanks for looking into that!

**Comment by sgoehringer** [comment]
Closing as dosage needs to move to MONDO
