### ISSUE TITLE
Correct inaccurate/incomplete ACI data on website

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#3]
Issue & Justification

This will group the five open issues/concerns from stakeholders concerning inaccurate or incomplete representation of existing ACI version ?.? data to the public.
- displays only first released report (even if failed), no context, incomplete representation
- gene-disease pairs not accurately being represented
- literature search date must be available for accurate age of assessment
- unclear delineation of early-rule out topic failures from actionable, easily mistaken, please correct
- the website browse curations page contains several inaccuracies in general - request details from stakeholder.

https://docs.google.com/document/d/1y_jXGScj7yuIuTBLWKYM25NBgYIYI9NOVkvwtolEBMo/edit#heading=h.qwxtvrchw7u4

**Comment by sgoehringer** [comment]
Had a good call with Kate (ACI) on Sept 26th.  Buttoning up the changes for the CMS to release next week.  Wrapping up changes to the search pages next week and provide access to ACI for QC.

**Comment by sgoehringer** [comment]
UI progress has been made but issue remains on displaying ACI curations for conditions and how the code that ingests the curation data is associating (bubbling) things up.

**Comment by tnavatar** [comment]
@sgoehringer Were you able to review your call with Kate and identify what needs to be done to complete this task?

**Comment by sgoehringer** [comment]
@tnavatar I am checking with Phil to confirm I the issue can still be reproduced.

**Comment by sgoehringer** [comment]
@tnavatar @plweller3 An update was committed to GITHUB to allow the current actionability page redirect to a page on the www.clinicalgenome website.  This update addresses one aspect of the original request.  You can see the commit https://github.com/clingen-data-model/clingen-knowledge/commit/85e56f41faf5ad34ff80b719980205cb42fe96eb  Please release this change to production.

**Comment by tnavatar** [comment]
Do you have this one @plweller3, or would you like me to release to production?

**Comment by plweller3** [comment]
I don’t think its ready for production.  I believe a few things still have to be done.

1:  Upload the conditions changes
2:  Set up production database
3:  Test

**Comment by tnavatar** [comment]
I can set up genegraph in production today—the one thing I was checking in on was whether we needed changes to the way genetic conditions beneath a given condition are represented or not. I think we were trying to figure out if this behavior was unwanted or not—either way. I can do this before or after getting Genegraph into production.

**Comment by sgoehringer** [comment]
@tnavatar @plweller3 ALL STOP

**Comment by sgoehringer** [comment]
@tnavatar @plweller3 This update is only for 85e56f4 and only effects the actionability list redirect.  NO RELEASE FOR GENEGRAPH changes.

**Comment by tnavatar** [comment]
Where’s the ticket for Genegraph changes?

**Comment by sgoehringer** [comment]
Due to confusion I am moving the Actionability redirect to the specific ticket.  https://github.com/clingen-data-model/clingen-knowledge/issues/12

**Comment by sgoehringer** [comment]
@tnavatar @plweller3 This ticket holds all of the original issues for the ACI changes that you are implementing for GeneGraph and one of those changes is for this list page redirect. This issue is still the original issue for the ACI display issues.  Feel free to open a GeneGraph only if you feel that will be helpful to track GeneGraph specific items.  This issue will stay open until the overall project for the ACI updates is released as this issue confirm

**Comment by sgoehringer** [comment]
Great work from the teams to move this forward.  On a call today (Dec 12) it was decided and communicated via notes shared over slack to move forward with the updates needed to support ACI support for MONDO and a curation day (Pizza Day) in late January 2020.  The Stakeholders understand that this may impact release of these updates and mean that we miss the deadline for this SP quarter.

**Comment by sgoehringer** [comment]
Items related to CSP-13... closing as new SP items will be issued for new items
