### ISSUE TITLE
SOP7 Support For Frontend

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#32]
Incorporate updates to support SOP7 for display.

**Comment by sgoehringer** [comment]
https://github.com/clingen-data-model/clingen-knowledge/commit/969a4f7cbf58e634ede5ddacb8e043514f60b19e

**Comment by sgoehringer** [comment]
@tnavatar updates were made to support the SOP7 release that the GCI is staging later this week.  The updates are minor.  I don't have test data from the GCI to trigger this but I don't expect an issue. They can released when you have time.  Let me know if you have issues.

**Comment by tnavatar** [comment]
Changes deployed; should be live in prod, changes in search2 failed due to local changes present in repo.

**Comment by sgoehringer** [comment]
Closing item... reopen if issues occur
