### ISSUE TITLE
Gene Express Curation HGNC Issue  (Report 6236)

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#33]
It was reported that https://search.clinicalgenome.org/kb/gene-validity/6236 display shows FAM65B (which is previous symbol for RIPOR2) in the report but the HGNC ID (HGNC:13872) is for RIPOR2.  Checking with Marina DiStefano if https://search.clinicalgenome.org/kb/gene-validity/6236 should be removed.

**Comment by sgoehringer** [comment]
Report 6236 was removed from Express JSON
https://github.com/clingen-data-model/data-exchange-shared-json/commit/78088e4f9ac9f0ee97a25654360ef08d75afa72e

**Comment by sgoehringer** [comment]
@tnavatar please re-run the JSON and/or remove the Gene Curation Report 6236.  Removal this report will allow GCI to proceed on their side.

This issue can be closed when the following are true;
Report https://search.clinicalgenome.org/kb/gene-validity/6236 isn't available
Links to report 6236 is not available on https://search.clinicalgenome.org/kb/genes/HGNC:13872

NOTE: A new curation will be published from the GCI so if a report does show for HGNC:13872 confirm the link is different that https://search.clinicalgenome.org/kb/gene-validity/6236 before re-openning

**Comment by tnavatar** [comment]
match (a:GeneDiseaseAssertion {perm_id: "6236"}) detach delete a;

**Comment by tnavatar** [comment]
This association has been removed from the website; it may take up to 10m for changes to reflect on the gene and disease pages.

**Comment by sgoehringer** [comment]
@tnavatar Thank you!  I'll keep an eye on the site to confirm removal and reassign you if needed.

**Comment by sgoehringer** [comment]
Confirmed the report was removed (not cached).  Closing ticket
