### ISSUE TITLE
Removal of pheochromocytoma paraganglioma gene curation

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#35]
A request was made and approved (by Sharon Plon, Courtney Lynn Thaxton and Xi Luo) to have the following disease validity reports removed from the website.

https://search.clinicalgenome.org/kb/gene-validity/8369
https://search.clinicalgenome.org/kb/gene-validity/8355
https://search.clinicalgenome.org/kb/gene-validity/8356
https://search.clinicalgenome.org/kb/gene-validity/8357
https://search.clinicalgenome.org/kb/gene-validity/8358
https://search.clinicalgenome.org/kb/gene-validity/8353
https://search.clinicalgenome.org/kb/gene-validity/8352
https://search.clinicalgenome.org/kb/gene-validity/8359
https://search.clinicalgenome.org/kb/gene-validity/8354
https://search.clinicalgenome.org/kb/gene-validity/8360
https://search.clinicalgenome.org/kb/gene-validity/8361
https://search.clinicalgenome.org/kb/gene-validity/8362
https://search.clinicalgenome.org/kb/gene-validity/8363
https://search.clinicalgenome.org/kb/gene-validity/8364
https://search.clinicalgenome.org/kb/gene-validity/8365
https://search.clinicalgenome.org/kb/gene-validity/8370
https://search.clinicalgenome.org/kb/gene-validity/8368
https://search.clinicalgenome.org/kb/gene-validity/8373
https://search.clinicalgenome.org/kb/gene-validity/8374
https://search.clinicalgenome.org/kb/gene-validity/8366
https://search.clinicalgenome.org/kb/gene-validity/8367
https://search.clinicalgenome.org/kb/gene-validity/8372
https://search.clinicalgenome.org/kb/gene-validity/8371

@tnavatar please confirm when complete.  Thanks!

**Comment by tnavatar** [comment]
Are these already gone from the gci express data?

**Comment by sgoehringer** [comment]
These were removed from the express data for the version where the MONDO was as the primary identifier.

**Comment by sgoehringer** [comment]
(Forgot to paste this)
https://github.com/clingen-data-model/data-exchange-shared-json/commit/370ffbc1f104e2a0cab87ae959571865ac7936ff

**Comment by tnavatar** [comment]
Would it be an acceptable solution then to ensure all GCI Express curations are removed apart from the ones already in the json file?

**Comment by sgoehringer** [comment]
Update released. Closed
