### ISSUE TITLE
Missing Gene - MIR96 (HGNC:31648)

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#36]
The production search site (and staging sites) don't have MIR96 (HGNC:31648) which is causing a Gene Disease Validity curation to not be displayed.  

It was discovered that MIR96 (HGNC:31648) - nonsyndromic genetic deafness (MONDO:0019497) is not showing on the website. Accessing the gene detail page directly returns an error.  https://search.clinicalgenome.org/kb/genes/HGNC:31648

Acceptances Criteria
- Gene detail page works - https://search.clingen.info/kb/genes/HGNC:31648
- Curation shows for MIR96 (HGNC:31648) - nonsyndromic genetic deafness (MONDO:0019497) when clicking on report - link unknown at this time
- Curation shows on Gene Disease Validity page (should happen automatically but confirm) - https://search.clinicalgenome.org/kb/gene-validity/
- Curation shows on nonsyndromic genetic deafness (MONDO:0019497) page (should happen automatically but confirm) - https://search.clinicalgenome.org/kb/conditions/MONDO_0019497
- MIR96 shows on all curations list pages - https://search.clinicalgenome.org/kb/curations/

**Comment by tnavatar** [comment]
I've added MIR96 to the KB as a one-off; this should be harmless but I was wary of loading all the pseudogenes into the database.

https://search.clinicalgenome.org/kb/genes/HGNC:31648

Would it be possible to notify a user with the ability to publish this curation to republish it? I would expect it to work now.

**Comment by sgoehringer** [comment]
@tnavatar user was notified... I will let you know if you need to revisit.  (Hopefully not!)
