### ISSUE TITLE
TBC1D24-DOORS Syndrome Curation Missing

### ISSUE THREAD

**Issue by mayherpatel** [clingen-data-model/clingen-knowledge#41]
TBC1D24-DOORS Syndrome curation is missing from the website. This GDA was curated by the HLGCEP.

The MONDO ID is: MONDO:0009079
The published link from the GCI is: https://search.clinicalgenome.org/kb/gene-validity/0fcb9839-6798-4195-8959-08d45bc63339--2018-09-25T14:41:38

**Comment by sgoehringer** [comment]
Additional background that may be helpful...
- The curation was not showing on the website prior to the recent release.
- The curation was was unpublished and republished to the website via the GCI

**Comment by tnavatar** [comment]
There is no record of this curation having been published in the streaming service. There are recent curations available on the service (as of 2020-03-09), so I do not suspect a general inability of the GCI to send updated publications. @mayherpatel could you contact the Stanford Helpdesk regarding this issue? It's possible there's an issue on that side, or there's a publication step remaining that needs to be done.

**Comment by mayherpatel** [comment]
This is resolved!
