### ISSUE TITLE
CDC14A - hearing impairment and infertile male syndrome curation missing

### ISSUE THREAD

**Issue by mayherpatel** [clingen-data-model/clingen-knowledge#42]
CDC14A - hearing impairment and infertile male syndrome (MONDO:0100069) curation missing from the website. This GDA was curated by the HLGCEP.

MONDO ID: MONDO:0100069
GCI Published Link: https://search.clinicalgenome.org/kb/gene-validity/144089d2-83ec-4c6c-8b43-9a4cae801d51--2018-09-21T15:58:24

**Comment by sgoehringer** [comment]
Additional background that may be helpful...
- The curation was not showing on the website prior to the recent release.
- The curation was was unpublished and republished to the website via the GCI

**Comment by tnavatar** [comment]
Same as #41 . I suspect the two issues have the same resolution.

**Comment by mayherpatel** [comment]
This is resolved!
