### ISSUE TITLE
MPC1L Curation Removal

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#45]
A test curation was added to the Dosage JIRA interface to test if a curation is automatically removed from the website when re-opened.  Upon further review of the scripts that send message to the streaming services it doesn't look like this will happen but the test was put through by the stakeholder to confirm.  

https://search.clinicalgenome.org/kb/genes/HGNC:44205

STEPS:
- Curation was added (DONE)
- Curation was changed to open to the stakeholder expects the curation to be removed (Feb 28 @10am)
- Check the search website to see if curation was automatically removed (Feb 28 @1pm)

RESULTS
- Findings will be added as a new comment

ACCEPTANCE/ACTION ITEMS
- IF curation automatically removed - NO ACTION NEEDED
- IF curation still shows on website 2 actions are required.
-- ACTION 1 
--- Manually remove the MPC1L dosage curation from the NEO4J database
--- Review the website and confirm the curation was removed
-- ACTION 2
--- Put start a new issue as a feature request with project plan on how to address the use case where an existing curation that is showing on the ClinGen website needs to be removed when the status from CLOSED to an OPEN, UNDER REVIEW, GROUP REVIEW, ETC, status.
--- Stakeholder informed this is a important priority as re-curations will be underway throughout 2020 and the dosage and ClinGen website can't be out of sync.

**Comment by sgoehringer** [comment]
RESULTS: The website was checked (https://search.clinicalgenome.org/kb/genes/HGNC:44205) and the curation is still showing.  This means that the script isn't removing curations after changes.  Action 1 and 2 should be done.

**Comment by sgoehringer** [comment]
@tnavatar this issue was just assigned to you.  Please review the items and proceed with Action 1 to the curation is removed.  Action 2 can be a topic for review next week.

**Comment by tnavatar** [comment]
Dosage curations connected to this gene have been removed:
    match (g:Gene {symbol: "MPC1L"})--(n) detach delete n;

**Comment by sgoehringer** [comment]
@tnavatar thanks!  Confirmed the removal.  Closing this issue
