### ISSUE TITLE
Curation not showing for GRIA3 - Complex Neurodevelopmental Disorder (MONDO:0100038)

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#48]
The stakeholders discovered that a curation initially done in the GCI but was manually changed in the GCI to a different disease isn't showing correctly on the website.

It looks that the original curation was for GRIA3 - X-linked syndromic intellectual disability (MONDO:0020119) but was changed to GRIA3 - Complex Neurodevelopmental Disorder (MONDO:0100038).  It seems that this is creating an issue for the website.  Though, something else may be going on as well.

@tnavatar can you check to see if the streaming service has received curation for GRIA3 - Complex Neurodevelopmental Disorder (MONDO:0100038) and the ingestion code isn't pulling that in and making all of the updates. @tnavatar or maybe something else is going on... open to other theories and ideas.  We've explored issues with GRIA3 but it wasn't known that the disease relationship was updated, at the time it seemed to be related to changes needed to update the affiliate.  

Next steps...
Still in discovery mode and working to find out if/what is going on and if/what data was sent to the streaming service.  Please update as additional facts become available.

**Comment by tnavatar** [comment]
All of the publications on this gene, including the most recent, are associated with x-linked syndromic ID

  [{"ontology" "MONDO",
    "curie" "MONDO:0020119",
    "uri" "MONDO0020119",
    "name" "X-linked syndromic intellectual disability",
    "iri" "http://purl.obolibrary.org/obo/MONDO_0020119"}]})

This suggests an issue on the Stanford side.

**Comment by sgoehringer** [comment]
@tnavatar Thank you!  
I'll pull you off as the assignee.  I'll reassign if we find it's something we need to address.
