### ISSUE TITLE
Gene Disease Validity Report Removal Request - ID 3218

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#49]
Stakeholders requested that AGTR2 - non-syndromic X-linked intellectual disability (https://search.clinicalgenome.org/kb/gene-validity/3218) to be removed.  This curation is in the process of curation in the GCI but the terms may change so it may not be overwritten.  The stakeholders requested that is be removed.

This curation was removed from the GeneExpress JSON.

Please remove, confirm the removal, and report back.

**Comment by tnavatar** [comment]
> match (a:GeneDiseaseAssertion {perm_id: "3218"}) detach delete a

This curation should now be removed from the production website.

**Comment by sgoehringer** [comment]
Confirmed removal.  Closing
