### ISSUE TITLE
Remove Legacy Curation (PKD1 - polycystic kidney disease 1)

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#50]
The Gene Small Call requested the following curation removed from the website. https://search.clinicalgenome.org/kb/gene-validity/9617

**Comment by sgoehringer** [comment]
@tnavatar following up on this request.

**Comment by sgoehringer** [comment]
Quick note that the JSON was updated on April 6

**Comment by tnavatar** [comment]
match (a:GeneDiseaseAssertion {perm_id: "9617"}) detach delete a;

**Comment by tnavatar** [comment]
Curation removed, to Scott for followup.
