### ISSUE TITLE
DMXL2 should have legacy curation removed

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#53]
There are two entries for DMXL2. A new curation came in from the GCI with a different MONDO so it wasn't able to remove the legacy curation.  Please remove https://search.clinicalgenome.org/kb/gene-validity/6237  This will be removed on the JSON data.

**Comment by sgoehringer** [comment]
Quick note, the JSON was updated

**Comment by tnavatar** [comment]
match (a:GeneDiseaseAssertion {perm_id: "6237"}) detach delete a;

**Comment by tnavatar** [comment]
Record removed, to Scott for confirmation.
