### ISSUE TITLE
GCI now sending "No Known Disease Relationship" as a classification

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#54]
Tracking a series topic from emails.
++++++++++++++++++++++++++++++++
The GCI began making updates to gene curation classifications to reflect recommendations by GenCC.  This means that some of the terms they were sending in the past will be different.  @tnavatar confirmed that when that happens the ingestion codes need to be updated so a process should be put in place to notify Tristan to be ready for those changes.  That said, they are now sending 

"No Known Disease Relationship". >> Formerly "No Evidence"
"No Classification" >> Unknown what this is and will be reviewed on a Gene Small call.

This looks to be the only changes they have made but the GenCC also recommends the following but the GCI doesn't seem to have made these changes...

GENCC                               GCI
Disputed Evidence.   >>> Disputed
Refuted Evidence      >>> Refuted 

The GCI hasn't made these changes and it is unknown if they will.  This need to be reviewed and reported back to the team if this needs to be accounted for.  At this time the users didn't expect it because it wasn't updated during the other updates.

This should provide enough background... the following comments/questions are related to if/what changes are needed to support these new curations coming in.

**Comment by sgoehringer** [comment]
Okay, withe the background out of the way. 

@tnavatar would it be possible to confirm that updates were made to the ingestion software to accept the new terms the GCI is sending?  At least for "No Known Disease Relationship" and "No Classification".  THANKS!

Once those are confirmed stakeholders will consider going back and updating curations made in the GCI after Aug 2019 which is when the SOP was updated with these new changes.  Manual changes are not approved to be made to legacy data or in the database. It was shared that curations classifications need originate in the GCI and republished. This will mean that a few curations will have different classification labels but this was approved by stakeholders on a web call April 24 2020.

**Comment by tnavatar** [comment]
@sgoehringer Changes were made to import these curations. Currently the label shows as "No Evidence" in all summary displays for any curations of these types. I think the desired behavior was that we would distinguish between "No Evidence" (old curations), and "No Known Disease Relationship" (new curations), including in the summary displays. Can you confirm this is true? If so I'll want to adjust the import scripts (and the database) to reflect this.

**Comment by sgoehringer** [comment]
Background…
The GCI now send "no known disease relationship” where curations prior this were sent with "No Reported Evidence”. Changing the "no known disease relationship” from the GCI to be "No Reported Evidence” has created a discrepancy.

Resolution...
On the GCI small call last week this topic was reviewed. The agreed path was to that the consumptions code should accept the new classification and the website should be able to display the new "no known disease relationship” classification while NOT altering any curations that currently show "No Reported Evidence”.  The GCI should be used to republish the curations to the site if the new classification should be displayed and legacy curations should be moved into the GCI and published.  The benefit of this process is we aren’t manually changing curation data in the search database and things don’t become out of sync with the streaming service and GCI.  

Implementation
When the code has been changed and released please update this ticket to let @sgoehringer know to contact the Stakeholders. They will then re-publish the handful of curations currently on the site that don't have the correct classifications showing.  It is expected the the re-curation will overwrite the past curations and replace it with the correct info without making database changes.

@tnavatar let me know if you have any follow up questions.

**Comment by tnavatar** [comment]
@sgoehringer A few questions:

* What time frame are the GCI team expecting a solution on? It would be more straightforward to make this part of the Genegraph deployment if it can wait a bit.
* Is 'no known disease relationship' the desired label for all curations previously noted as 'no reported evidence'? If so, it would be simpler and preferable to update the label for all curations to 'no known disease relationship'. Was the GCI group aware this was an option and did they have a reason for rejecting it?

**Comment by sgoehringer** [comment]
@tnavatar feedback below... 
Question #1 - Before gene graph... if this isn't possible please let me know 
Question #2 - Yes, the Gene Curation group was made aware of your proposal.  It wasn't selected because it would change curations that have been published with a new label/different label and some of those curations may be associated with publications.  The currently implementation also isn't ideal because the label is different from the GenCC label and different from what they set in the GCI. The stakeholders want BOTH curation labels to shown on the website. Curations to date will have the original "No Reported Evidence" (I believe that is what it was) and they are seeking to have your ingestion code accept "No Known Disease Relationship". Ones that weren't associated correctly recently will be republished so the new label is used. This ensures that curations published in the past aren't altered.

1 - Please let me know if you have follow up
2 - Please let me know when this update is slated so I can communicate with the stakeholders

P.S. It will be curious if the recreation process trips over the other publishing issue discovered in #56

**Comment by sgoehringer** [comment]
This request won't be implemented as stated above.  Will be tabled until GeneGraph is released later this year.
