### ISSUE TITLE
Contributors not showing as expected for TRDN - long QT syndrome... 

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#55]
https://search.clinicalgenome.org/kb/gene-validity/1278bd6a-6ac7-4556-87ea-f860027b2da5--2020-04-24T16:00:00

Review the above and see why Long QT Syndrome Long QT Syndrome GCEP looks to be showing twice.  Check the data and see what's what.

**Comment by sgoehringer** [comment]
This is another test example
https://search.clinicalgenome.org/kb/gene-validity/26ae5799-567b-431b-b981-3bc2f8635802--2018-08-23T16:00:00

**Comment by sgoehringer** [comment]
@tnavatar a quick UX patch went out for this issue.  https://github.com/clingen-data-model/clingen-knowledge/commit/271f738198c0085b74f8d15df24cd8e388eb7659  This commit only has one change to a view, please confirm when you pull.  Can you sneak in this release quickly.  Thank you.

**Comment by tnavatar** [comment]
Should be sorted, note that there are problems with search2 that prevent this from being deployed there automatically:

➜  clingen-knowledge git:(master) ✗ ansible-playbook -i deploy/prod.yml deploy/deploy.yml 

PLAY [webservers] ********************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************
ok: [search2.clinicalgenome.org]
ok: [search.clinicalgenome.org]

TASK [Checkout or update repository] *************************************************************************************
fatal: [search2.clinicalgenome.org]: FAILED! => {"before": "2a59a7447386f7581640daa45e92773b9d249cea", "changed": false, "msg": "Local modifications exist in repository (force=no)."}
changed: [search.clinicalgenome.org]

TASK [Bundle gems] *******************************************************************************************************
changed: [search.clinicalgenome.org]

TASK [Precompile assets] *************************************************************************************************
changed: [search.clinicalgenome.org]

TASK [Restart nginx] *****************************************************************************************************
changed: [search.clinicalgenome.org]
	to retry, use: --limit @/Users/tristan/code/clingen-knowledge/deploy/deploy.retry

PLAY RECAP ***************************************************************************************************************
search.clinicalgenome.org  : ok=5    changed=4    unreachable=0    failed=0   
search2.clinicalgenome.org : ok=1    changed=0    unreachable=0    failed=1

**Comment by sgoehringer** [comment]
@tnavatar thanks!  Should the search2 issues be broken into a different issue or is this more of a headsup?

**Comment by tnavatar** [comment]
Probably create a different issue—please assign the issue to Phil if you do.

**Comment by sgoehringer** [comment]
Release UX checked... closing
