### ISSUE TITLE
Double Curation For Gene "GRIA3" - Remove 2017 Curation

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#6]
Reported By: "Kelly A. Toner" <ktoner1@geisinger.edu>
I just had to make updates to an evidence summary for a gene that was curated back in 2017 (GRIA3). When I updated the entry, it ended up adding an entry to the website, rather than just updating the one that is there (see below). I need the one dated 9/9/19 to stay on the website and the other one to be removed. Additionally, the date for the 9/9/19 entry really should be the 10/20/17 date, since that is when the curation was approved. Are these issues that you guys can help me with or do I need to talk to the Stanford team?

Scott Comment: 
It looks like the one from back in 2017 is a legacy curation done in the Gene Express tool.  It looks like the MONDO ID’s are slightly different.  Tristan, would it be possible to pull that one?

**Comment by tnavatar** [comment]
I removed the legacy curation from the database. @sgoehringer would it be possible to remove this curation from the GC Express archive so that we don't accidentally re-introduce it, or has that already been done?

**Comment by sgoehringer** [comment]
@tnavatar sure thing!  Can you confirm that the scripts are pulling from https://raw.githubusercontent.com/clingen-data-model/data-exchange-shared-json/master/json-from-gene-express/ClinGen-Gene-Expess-Data-03272019.json

**Comment by tnavatar** [comment]
Confirmed!

**Comment by sgoehringer** [comment]
@tnavatar this was removed from the JSON.  Let me know if you have any issues related to this.  The commit can be found at https://github.com/clingen-data-model/data-exchange-shared-json/commit/5fc575a9dc7fb59cbb579a904fd9685d8ffb5318  Going to close this issue
