### ISSUE TITLE
Actionability MYLK showing with a curation but the ACI doesn't have one

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#61]
@tnavatar please review MYLK to see why a AWG curation is showing.  I checked the ACI and a curation doesn't show for MYLK in their system.  https://search.clinicalgenome.org/kb/genes/HGNC:7590

Please advise with what you find early this week (May 11) as I have a call with them on May 14th.

**Comment by tnavatar** [comment]
That curation used to have MYLK in it, but no longer does; the import code did not take into account a gene being removed from a curation. Purging previous curations and re-running the import will address the issue. This will need to be done regardless as part of the CSP-14 resolution.

**Comment by sgoehringer** [comment]
@tnavatar I am testing CSP-14 on search2 and I see MYLK showing for the report. Shouldn't that have been removed by the new import process?

**Comment by sgoehringer** [comment]
Remove the MYLK relationship for report AC134 so the gene doesn't show related to this curation when searched.  This was updated in their data but from my understanding we are not updating the records.  This allows CSP-13 to wrap up

**Comment by tnavatar** [comment]
neo4j> match (a:ActionabilityAssertion)-[r:has_subject]->(g:Gene {entrez_id: "4638"}) where a.iri ends with "AC134" delete r;
