### ISSUE TITLE
MUT, MMADHC, MMACHC, MMAB, MMAA, MMEE - Report AC122 typo in the report label

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#62]
MUT, MMADHC, MMACHC, MMAB, MMAA, MMEE - Report AC122 typo in the report label. I believe “Acidemia" was mistyped as “Academia”. 

This issue was created to track what may become a manual override.  Waiting for AWG feedback.

**Comment by sgoehringer** [comment]
Update the label associated in the report to correct and issue.  This was updated on their side but we are not consuming their data

CURRENT:
label: Methylmalonic Academia - MUT, MMAA, MMAB, MMADHC, MCEE, MMACHC

REQUEST:
label: Methylmalonic Acidemia - MUT, MMAA, MMAB, MMADHC, MCEE, MMACHC

**Comment by tnavatar** [comment]
match (a:ActionabilityAssertion) where a.iri ends with "AC122" set a.label = "Methylmalonic Acidemia - MUT, MMAA, MMAB, MMADHC, MCEE, MMACHC";
