### ISSUE TITLE
Legacy Curation Removal PKP2 - report 8753

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#64]
A request to remove an older curations record for PKP2 that was performed and approved by the UNC Biocuration Core, and entered as the Gene curation express, it is for the PKP2 gene and the UUID is https://search.clinicalgenome.org/kb/gene-validity/8753

**Comment by tnavatar** [comment]
match (a:GeneDiseaseAssertion {perm_id: "8753"}) detach delete a;
