### ISSUE TITLE
MONDO term out of date - Should be arrhythmogenic cardiomyopathy with woolly hair and keratoderma

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#65]
The audit of ACMG59 genes came across the following issue for the gene DSP.  On the website its disease term is displayed as "dilated cardiomyopathy with woolly hair and keratoderma."  In the GCI the term is displayed as "arrhythmogenic cardiomyopathy with woolly hair and keratoderma."  The MONDO is the same in both locations, and MONDO displays the "arrhythmogenic" version.  Why is the web display different?  I am not an expert in cardiovascular disorders, but I believe dilated and arrhythmogenic cardiomyopathy are two different things, so this matters

++++++
Email from Tristan - Best guess before investigating is that the label on the term changed in MONDO; and our website is based on an older version. An update of MONDO and the ability to update MONDO more reliably and frequently is planned as part of the website data store update.

++++++
Next steps
- Checking with stakeholders and the importance of the update/change and will report back

**Comment by tnavatar** [comment]
Update label on term in database

**Comment by tnavatar** [comment]
match (r:DiseaseConcept {iri: "http://purl.obolibrary.org/obo/MONDO_0011581"}) set r.label = "arrhythmogenic cardiomyopathy with woolly hair and keratoderma";

**Comment by sgoehringer** [comment]
Confirmed!  Closing
