### ISSUE TITLE
Display MOI for Gene Validity

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#7]
https://search.clinicalgenome.org/kb/gene-validity/

Below are two examples where mode of inheritance is needed to be displayed.
GRIA1
EDNRB

Follow up: make sure the on the Gene and Disease listing pages two curations show when multiple inheritance.  I believe the code removes the second curation which should show.

https://docs.google.com/document/d/1VKaI0YkkGQSOgVzLorhSDnk1ML8rVmEZa5Xxk-v2cvU/edit#heading=h.qwxtvrchw7u4

**Comment by sgoehringer** [comment]
This known issue is moving to a higher priority as more curations are being done on gene-disease with different MOI. Spending time next week (Oct1) with Phil to review code and plan the implementation.

**Comment by sgoehringer** [comment]
Update - this work is being shared with Stakeholders.  It is staged to release when ACI updates are complete.

**Comment by sgoehringer** [comment]
Untangle this work from genegraph Branch so we can release prior to Genegraph
https://github.com/clingen-data-model/clingen-knowledge/issues/27

**Comment by sgoehringer** [comment]
Quick ticket update to capture two examples for testing.

a gene with multiple disease associations but only one is showing: TECTA has classifications in the GCI for AD and AR nonsyndromic hearing loss but only the AD one is displayed
https://search.clinicalgenome.org/kb/genes/HGNC:11720

**Comment by sgoehringer** [comment]
Quick update based on communication today (Dec 19).  This update is slated for first weeks of January.

**Comment by dazzariti** [comment]
Additional example - LZTR1 example here https://search.clinicalgenome.org/kb/genes/HGNC:6742 - only the AR Noonan Syndrome curation shows (Limited), but there is also an approved AD Noonan Syndrome curation (Strong) that doesn't show up under the results.

**Comment by sgoehringer** [comment]
Great, thank you

**Comment by sgoehringer** [comment]
Released
