### ISSUE TITLE
Removal request for Gene Validity Report #8440

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#72]
Stakeholders have requested the removal of Gene Validity Report #8440
https://search.clinicalgenome.org/kb/gene-validity/8440

Please advise when complete to confirm the removal.  Thank you!

**Comment by tnavatar** [comment]
match (a:GeneDiseaseAssertion {perm_id: "8440"}) detach delete a;
0 rows available after 27 ms, consumed after another 0 ms
Deleted 1 nodes, Deleted 5 relationships
