### ISSUE TITLE
Double curation for GRIA3, ARHGEF6, SLC6A4

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#8]
It looks that the GCI sent two curations (in the past) for the same gene-disease-MOI.  During discovery it is believed that this curation was first started by a single person and then the GCI ran a script to transfer the curation to an affiliation.  The URLs are different which I believe means that the curation ID is different.  This may be the cause of the issue.  Unsure if the fix needs to happen at the GCI, streaming, ingestion.  

I welcome your thoughts while I am explore this more with Kelly T.

https://search.clinicalgenome.org/kb/gene-validity/25f94660-0a8d-4f3a-8f6c-dde1b38a8ab7--2017-10-20T16:00:00
https://search.clinicalgenome.org/kb/gene-validity/25f94660-0a8d-4f3a-8f6c-dde1b38a8ab7--2019-09-09T17:33:42

**Comment by tnavatar** [comment]
On ingest of a new message with the same UUID, the intake script should set a relationship from the old to the new, ensuring that the old curation does not display. In general this has been working; will need to investigate why it did not in this instance.

**Comment by sgoehringer** [comment]
@tnavatar yeah, this is the first time we've seen this.  It seems to have worked fine for curation updates since it was originally release.  I think the edge case that came up here was this curation was transferred to an affiliation and it may have generated a different curation ID... but the original is either not in the GCI UI or if it is still in the GCI didn't have a status changed.  I'll share more (Today/Monday) as I work with Kelly.

**Comment by sgoehringer** [comment]
**Call Notes (Scott & Kelly - Sept 17)**
The purpose of the call was to review the issue that looked to have only been an issue for GRIA3 but we discovered that two more genes are effected (ARHGEF6, SLC6A4).  At first it looked that the issue was caused after the GCI needed to change curations from a user to an affiliation.  We noticed this was common fro GRIA3 and ARHGEF6 but change wasn't performed on SLC6A4.  The user to affiliation change may be causing an issue but it doesn't look to be the main issue.

Upon further review it was noticed that each of these curations was originally curated with a set date and then a curator needed to go in and republished with a new date.  This date change looks change the identifier used as the URL for the curation.  (Examples below)

**GRIA3**
https://search.clinicalgenome.org/kb/gene-validity/25f94660-0a8d-4f3a-8f6c-dde1b38a8ab7--2019-09-09T17:33:42
https://search.clinicalgenome.org/kb/gene-validity/25f94660-0a8d-4f3a-8f6c-dde1b38a8ab7--2017-10-20T16:00:00

**ARHGEF6**
https://search.clinicalgenome.org/kb/gene-validity/f846d8a2-27c2-4bb4-9c16-524a22ff5d3b--2018-06-28T18:46:01
https://search.clinicalgenome.org/kb/gene-validity/d248ef99-6ff8-43d8-a24e-dfce6b2db1c8--2018-05-17T16:00:00

**SLC6A4**
https://search.clinicalgenome.org/kb/gene-validity/cc4b0612-0a53-4e36-b737-5c0f49a387a1--2018-09-24T20:22:51
https://search.clinicalgenome.org/kb/gene-validity/cc4b0612-0a53-4e36-b737-5c0f49a387a1--2018-05-02T16:00:00

A theory at this time is that the website isn't able to match what should be a curation update (replace a prior curation with a new curation) because the GCI may be sending a different identifier or if they are sending the prior identifier in the data package the ingestion scripts aren't matching as expected.  

A few other items of note... 
- The curations look to have all started in the GCI and are not legacy curations from gene express
- The curator needed to change the curation date for each of the curations
- The date change is interesting because updates that look have simply been a typo change, where the date doesn't change, don't seem to have had this issue (though this hasn't been completely explored)

**Comment by sgoehringer** [comment]
@tnavatar when you have a chance when you get in (I don't recall if you are back today or Thursday) can you review the issue notes above and let me know if you have thoughts/questions.  I'm glad to chat if that is helpful.

**Comment by tnavatar** [comment]
On studying this issue and review of the code used to import new curations,i I had added code to check whether a curation is newer or older than than the existing, valid curation for a given ID. I had wanted to guard against the case where messages were received out-of-order. These are all publications who had their date adjusted to an (earlier) date, meaning that the import script treated them as less recent than the publication currently in the system.

I can manually tweak the database to address the immediate issue. I'm not sure I want to tweak the import logic in production without first ensuring against unintended consequences.

**Comment by tnavatar** [comment]
Just to confirm, @sgoehringer,  in every case listed above, is the 'older' curation actually the correct one?

**Comment by sgoehringer** [comment]
@tnavatar 
Part 1 - Thanks for checking into things and your explanation does seem to be inline with what has been noticed.  The date change was the key, we didn't find others with issues that were updated.  I am confirming with Kelly that these curations all had curation dates that changed to be 'older' that the initial.  Stay tuned.

Part 2 - If you make a manual change what are the updates needed to ensure these curations don't make it back into the database if/when the streaming service is used to rebuild the database?

**Comment by sgoehringer** [comment]
Call Notes (@sgoehringer and @tnavatar)
Confirm with Kelly that the curation updated dates were older for each of the curations
IF TRUE - Action Items
- Implement a change to the code that doesn't rely on the curation date to check to account for possible out-of-order data in the streaming service.
- Perform these set up updates with issue #9 #8
- Test updates on staging server to confirm changed and test #9 #8
IF FALSE - Action Items
- Continue testing/review to track down other possible causes

**Comment by sgoehringer** [comment]
Released
