### ISSUE TITLE
Remove double MONDO IDs from website

### ISSUE THREAD

**Issue by sgoehringer** [clingen-data-model/clingen-knowledge#9]
SP: https://broadinstitute.atlassian.net/browse/CSP-46

Known website bug - for gene curations entered via Gene Curation Express (GCE): If the curator entered both a MONDO ID and an OMIM ID in GCE, and the two terms were not an exact wording match (regardless of whether or not they are conceptually the same thing), the website matched with two distinct MONDO terms and displays the same curation twice (once under each term).  The result is that, to the user, it looks like there are more gene curations than intended.

Work has been done to go through the Gene Curation Express curations and associating those with the proper MONDO ids.  Seeking feedback from @tnavatar to confirm that making updates to the Gene Curation Express JSON by either 1) adding the MONDO or 2) adding the MONDO and removing the OMIM, will be able to address this issue.

**Comment by sgoehringer** [comment]
Hey Tristan, just following up on this one. "Seeking feedback from @tnavatar to confirm that making updates to the Gene Curation Express JSON by either 1) adding the MONDO or 2) adding the MONDO and removing the OMIM, will be able to address this issue."  Glad to chat about this if you would like.

**Comment by tnavatar** [comment]
The data in the GCE is based on ORPHA and OMIM, not MONDO. We should associate every remaining curation in the GCE with a single ID of either ORPHA or OMIM (and possibly MONDO, though will need to validate that the init script can handle that). It's possible that this could be done automatically for the cases where the two terms do match, and we can at least flag the issue when they don't.

In the long run, we'll need to support this data at least until every curation is in the GCI, and possibly beyond that, assuming we have a use and a need to display legacy data. This means that we'll need a transformation from this data into the SEPIO format, which will properly only support one disease association.

**Comment by sgoehringer** [comment]
Call Notes (@sgoehringer and @tnavatar)
The current GCE ingestion code doesn't do anything with the MONDO terms but Tristan felt that it would be simple change to drop support for OMIM/ORPHANET and only go with the MONDO term provided to make the relationships.  Background, a manual audit was completed and MONDO terms were provided for each curation.

Action Items
- Move forward with including the MONDO terms into the GCE JSON data
- Update ingestion scripts to only use MONDO terms
- Perform these set up updates with issue #10 #8 
- Test updates on staging server to confirm changed and test  #10 #8

**Comment by sgoehringer** [comment]
@tnavatar The Gene Express Data was updated and a new file created in GItHub.  https://github.com/clingen-data-model/data-exchange-shared-json/commit/854c2d4a54c506d2cb2cd7905f208abfd5574f03#diff-9d855cc785b5e32e6ed2427138e8ed07. Let me know if you want this file broken into individual files.  The work related to this ticket is to have the ingestion code use the new MONDO data that was added as the only way a curation is related to a condition.  OMIM and ORPHANET shouldn't be used.  Also, this file removes any legacy curations that the GCI has overwritten.

**Comment by sgoehringer** [comment]
Closing post release
